[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#070A0F"
secondaryBackgroundColor = "#0E1621"
textColor = "#EAF2FF"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
